stages:
  - build

image: debian:bookworm

variables:
  DEBIAN_FRONTEND: "noninteractive"

build-pigweed:
  stage: build
  variables:
    SCALENODE_CPU: 8
    SCALENODE_RAM: 16384
    SCALENODE_DISK: 200
  script:
    - apt update
    - apt install -y build-essential git wget python3 python-is-python3
    - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64
    - chmod +x bazelisk-linux-amd64 && mv bazelisk-linux-amd64 /usr/bin/bazelisk
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${PIGWEED_REPO}".insteadOf "https://github.com/antmicro/pigweed.git"
    - git submodule update --init --recursive
    - for file in $(ls examples); do bazelisk build //examples/${file}:all; done
    - mkdir out
    - cp -Lr bazel-bin/examples/* out
  artifacts:
    paths:
      - out

