stages:
  - build

image: debian:bookworm

variables:
  DEBIAN_FRONTEND: "noninteractive"

build-pigweed:
  stage: build
  variables:
    SCALENODE_CPU: 8
    SCALENODE_RAM: 16384
  script:
    - apt update
    - apt install -y build-essential git wget python3 python-is-python3
    - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64
    - chmod +x bazelisk-linux-amd64 && mv bazelisk-linux-amd64 /usr/bin/bazelisk
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${PIGWEED_REPO}".insteadOf "https://github.com/antmicro/pigweed.git"
    - wget https://go.dev/dl/go1.22.6.linux-amd64.tar.gz
    - tar -C /usr/local -xzf go1.22.6.linux-amd64.tar.gz
    - export PATH=$PATH:/usr/local/go/bin
    - git submodule update --init --recursive
    - pushd third_party/pigweed/third_party/mcuxpresso/
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${MCUXPRESSO_REPO} sdk
    - pushd sdk
    - git checkout origin/SDK_2.16.000_EVK-MIMXRT595
    - popd && popd
    - pushd third_party/boringssl
    - python src/util/generate_build_files.py gn
    - popd
    - source bootstrap.sh
    - gn gen out
    - ninja -C out
  artifacts:
    paths:
      - out

