stages:
  - build

image: debian:bookworm

variables:
  DEBIAN_FRONTEND: "noninteractive"

build-pigweed:
  stage: build
  variables:
    SCALENODE_CPU: 8
    SCALENODE_RAM: 16384
  script:
    - apt update
    - apt install -y build-essential git wget python3 python-is-python3
    - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64
    - chmod +x bazelisk-linux-amd64 && mv bazelisk-linux-amd64 /usr/bin/bazelisk
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${PIGWEED_REPO}".insteadOf "https://github.com/antmicro/pigweed.git"
    - git submodule update --init --recursive
    - pushd third_party/pigweed/third_party/mcuxpresso/
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${MCUXPRESSO_REPO} sdk
    - pushd sdk
    - git checkout origin/SDK_2.16.000_EVK-MIMXRT595
    - popd && popd
    - bazelisk build --config mimxrt595_evk_freertos //examples/01_bluetooth:bluetooth
    - bazelisk build --config mimxrt595_evk_freertos //examples/02_usb_fastboot:usb_fastboot
    - mkdir out
    - cp -r bazel-bin/examples/* out
  artifacts:
    paths:
      - out

