# This is a pw_console config file that defines a default window layout.
# For more info on what can be added to this file see:
#   https://pigweed.dev/pw_console/py/pw_console/docs/user_guide.html#configuration
config_title: pw_console

# Window layout
windows:
  # Left split with tabbed views.
  Split 1 tabbed:
    Python Repl:
      hidden: False
  # Right split with tabbed views.
  Split 2 stacked:
    Device Logs:
      hidden: False
    Host Logs:
      hidden: False

# Color options
ui_theme: dark
# ui_theme: nord
# ui_theme: high-contrast-dark
code_theme: pigweed-code
# code_theme: pigweed-code-light
# code_theme: gruvbox-dark
swap_light_and_dark: False

# Display options
spaces_between_columns: 2
window_column_split_method: vertical
# window_column_split_method: horizontal
# hide_date_from_log_time: True
