/*
 * Copyright 2019 NXP.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made
 *to this file will be overwritten if the respective MCUXpresso Config Tools is
 *used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v6.0
processor: MIMXRT595S
package_id: MIMXRT595SFFOC
mcu_data: ksdk2_0
processor_version: 0.0.0
board: MIMXRT595-EVK
functionalGroups:
- name: BOARD_InitPeripherals
  called_from_default_init: true
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'msg'
- type_id: 'msg_6e2baaf3b97dbeef01c0043275f9a0e7'
- global_messages: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

#include "MIMXRT595S_cm33.h"
#include "fsl_dma.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void i2c_release_bus_delay(void) {
  uint32_t i = 0;
  for (i = 0; i < 100; i++) {
    __NOP();
  }
}

void BOARD_I3C_ReleaseBus(void) {
  uint8_t i = 0;

  GPIO_PortInit(GPIO, 2);
  BOARD_InitI3CPinsAsGPIO();

  /* Drive SDA low first to simulate a start */
  GPIO_PinWrite(GPIO, 2, 30, 0U);
  i2c_release_bus_delay();

  /* Send 9 pulses on SCL */
  for (i = 0; i < 9; i++) {
    GPIO_PinWrite(GPIO, 2, 29, 0U);
    i2c_release_bus_delay();

    GPIO_PinWrite(GPIO, 2, 30, 1U);
    i2c_release_bus_delay();

    GPIO_PinWrite(GPIO, 2, 29, 1U);
    i2c_release_bus_delay();
    i2c_release_bus_delay();
  }

  /* Send stop */
  GPIO_PinWrite(GPIO, 2, 29, 0U);
  i2c_release_bus_delay();

  GPIO_PinWrite(GPIO, 2, 30, 0U);
  i2c_release_bus_delay();

  GPIO_PinWrite(GPIO, 2, 29, 1U);
  i2c_release_bus_delay();

  GPIO_PinWrite(GPIO, 2, 30, 1U);
  i2c_release_bus_delay();
}

void BOARD_InitPeripherals(void) {
  DMA_Type* dmaBases[] = DMA_BASE_PTRS;
  BOARD_I3C_ReleaseBus();

  for (unsigned int i = 0; i < sizeof(dmaBases) / sizeof(dmaBases[0]); i++) {
    DMA_Init(dmaBases[i]);
  }
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void) { BOARD_InitPeripherals(); }
